### ISSUE TITLE
Test Code Size Reduction with Terser

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library_color-palettes#10]
# Description

We want to see if we can apply [terser](https://terser.org/) to the JavaScript output by the TypeScript compiler.

Does that minification significantly reduce the unpacked size of the NPM package?

# Tasks

- [x] install terser dependency
- [x] configure terser to run on TypeScript compiler output
- [x] deploy to npm to check new package size

**Comment by azurepolarbear** [comment]
Completed with Rollup bundler updates.
