### ISSUE TITLE
Feature Request - Add Color Contrast Checking and Calculations

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library_color-palettes#20]
# Description

Use [color contrast](https://www.npmjs.com/package/color-contrast) npm package to check for contrast between color values.

Add unit test to inform if there is a AAA passing contrast pair within the palette.

Add field to palettes to store valid color contrast pairs.

Add unit test to make sure all color contrast pairs are valid pairs (ratio > 7).

# Tasks

- [ ] install [color contrast](https://www.npmjs.com/package/color-contrast) package
- [ ] add methods to base library for evaluating contrast and WGAC compliance
  - [ ] contrast ratio
  - [ ] AA compliance
    - [ ] small text
    - [ ] large text
  - [ ] AAA compliance
    - [ ] large text
    - [ ] small text
- [ ] implement/add unit test for all palettes
  - [ ] passing if there is at least one AAA small text compliant pair in the palette
- [ ] decide what to do with palettes that do not pass
- [ ] add field to palettes to store valid AAA color contrast pairs (ratio > 7)
- [ ] implement/add unit test for all palettes
  - [ ] passing if all color contrast pairs are valid pairs (ratio > 7)
