### ISSUE TITLE
Feature Request - Add Color Name Request to Library

### ISSUE THREAD

**Issue by azurepolarbear** [brittni-and-the-polar-bear/generative-art-library_color-palettes#21]
# Description

Add request for color names from the [Color Name API](https://www.npmjs.com/package/color-name-api?activeTab=readme).

# Tasks

- [ ] research how to properly make a REST call in TypeScript
- [ ] integrate getting color names into library
- [ ] get colors for palettes and generative color
