### ISSUE TITLE
Implement Unit Test for Color Uniqueness

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library_color-palettes#7]
# Description

For every color in the palettes, the hexstring, rgb, and hsl must all be unique. If there is any color that shares any of those values, they should be consolidated.

# Tasks

If you are familiar with the development requirements, place the tasks you expect will need to be completed for this
feature here.

- [x] develop test for hexstring uniqueness
- [x] develop test for rgb uniqueness
- [x] develop test for hsl uniqueness
- [x] develop test for name uniqueness
- [x] develop test for htmlName uniqueness
- [x] develop test for wikipediaName uniqueness
- [x] test all colors
